# Generated by Django 5.2 on 2025-04-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crianca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateField()),
                ('data_validade', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('crianca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='crianca.crianca')),
            ],
        ),
    ]
