# Generated by Django 5.2 on 2025-05-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
