# Generated by Django 5.2 on 2025-05-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crianca', '0002_crianca_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True, verbose_name='Presente?')),
                ('justificativa_falta', models.TextField(blank=True, null=True, verbose_name='Justificativa da Falta')),
                ('alimentacao_detalhes', models.TextField(blank=True, verbose_name='Detalhes da Alimentação')),
                ('comportamento_notas', models.TextField(blank=True, verbose_name='Notas sobre o Comportamento')),
                ('atividades_descricao', models.TextField(blank=True, verbose_name='Descrição das Atividades')),
                ('recado_equipe', models.TextField(blank=True, verbose_name='Recado da Equipe para os Pais')),
                ('observacao_pais', models.TextField(blank=True, null=True, verbose_name='Observações dos Pais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_diarias', to='crianca.crianca')),
            ],
            options={
                'verbose_name': 'Registro da Agenda Diária',
                'verbose_name_plural': 'Registros da Agenda Diária',
                'ordering': ['-data', 'crianca__nome'],
                'unique_together': {('crianca', 'data')},
            },
        ),
        migrations.CreateModel(
            name='AnexoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_agenda/%Y/%m/%d/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agenda_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='agenda.agendadiaria')),
            ],
            options={
                'verbose_name': 'Anexo da Agenda',
                'verbose_name_plural': 'Anexos da Agenda',
                'ordering': ['-criado_em'],
            },
        ),
    ]
