# Generated by Django 5.2 on 2025-05-27 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('lembrete_pagamento', 'Lembrete de Pagamento'), ('status_pagamento', 'Status de Pagamento'), ('aviso_evento', 'Aviso de Evento'), ('novo_anexo_agenda', 'Novo Anexo na Agenda')], default='geral', max_length=30, verbose_name='Tipo da Notificação')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida?')),
                ('link_acao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de Ação (Opcional)')),
                ('texto_link_acao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto do Link de Ação')),
                ('urgente', models.BooleanField(default=False, verbose_name='Urgente?')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='responsavel.responsavel', verbose_name='Responsável Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
