# Generated by Django 5.2 on 2025-05-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('descricao', models.CharField(default='Mensalidade Encanto Kids', max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('processando', 'Processando')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('metodo_pagamento_efetuado', models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Método de Pagamento Efetuado')),
                ('link_boleto', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Boleto')),
                ('codigo_pix', models.TextField(blank=True, null=True, verbose_name='Código PIX (Copia e Cola)')),
                ('qr_code_pix_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do QR Code PIX')),
                ('id_transacao_gateway', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='ID da Transação no Gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='responsavel.responsavel', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-data_vencimento', 'responsavel__nome'],
            },
        ),
    ]
