# Generated by Django 5.2 on 2025-05-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacote', '0001_initial'),
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='responsavel.responsavel')),
                ('tipo_de_pacote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacote.pacote')),
            ],
        ),
    ]
