# Generated by Django 5.2 on 2025-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_criancas/'),
        ),
    ]
